# Generated by Django 6.1.1 on 2026-09-16 09:13

import django.db.models.deletion
import main.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('QUOTE_RECEIVED', 'Customer — quote request received'), ('QUOTE_SENT', 'Customer — your quote is ready'), ('STAFF_NEW_QUOTE', 'Staff — new quote request'), ('PAYMENT_REMINDER', 'Customer — payment reminder')], max_length=40, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True, help_text='Opening paragraph. Supports {name} and {quote_number}.')),
                ('outro', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "A4", "2m x 1m banner", "Door decal"', max_length=200)),
                ('pricing_type', models.CharField(choices=[('FLAT_RATE', 'Flat rate'), ('PER_METER', 'Per square metre'), ('PER_UNIT_RANGE', 'Ranged (from/to)'), ('CUSTOM_SIZE_FORMULA', 'Custom size (rate x size)')], default='FLAT_RATE', max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Flat price, or the per-square-metre rate for size-based rules.', max_digits=10)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_label', models.CharField(blank=True, default='each', max_length=50)),
                ('min_qty', models.PositiveIntegerField(default=1)),
                ('gst_inclusive', models.BooleanField(default=False, help_text='Tick if base_price already includes GST.')),
                ('requires_dimensions', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Short emoji or icon key used on the service cards.', max_length=100)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UrgentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='INDIVIDUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('access_token', models.CharField(default=main.models._token, editable=False, max_length=64, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('REVISED', 'Revised'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('urgent_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='GST-exclusive discount.', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_override', models.DecimalField(blank=True, decimal_places=2, help_text='Set to bypass the calculated total entirely.', max_digits=12, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('customer_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal only — never shown to customers.')),
                ('decline_reason', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='main.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, help_text='Free-text client, used for imported and manual rows with no customer record.', max_length=255)),
                ('job_details', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('invoice_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt_no', models.CharField(blank=True, max_length=100)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not paid'), ('PARTIAL', 'Partial'), ('TBC', 'TBC')], db_index=True, default='NOT_PAID', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH_CHQ', 'Cash / Cheque'), ('PO_ON_ACCOUNT', 'P.O. on account'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH_CHQ', max_length=30)),
                ('status_is_manual', models.BooleanField(default=False, help_text='Keeps a hand-set status (e.g. TBC) from being overwritten by the balance rule.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='main.customer')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='main.quote')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, help_text='Free-text size label.', max_length=200)),
                ('width_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('artwork', models.FileField(blank=True, null=True, upload_to='artwork/%Y/%m/')),
                ('is_urgent', models.BooleanField(default=False)),
                ('added_by_staff', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('pricing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pricingrule')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.quote')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.servicecategory')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='main.servicecategory'),
        ),
    ]
