# Generated by Django 6.1.1 on 2026-09-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Describes the photo for screen readers. Falls back to the caption.', max_length=200)),
                ('is_hero', models.BooleanField(default=False, help_text='Front this image on the service card.')),
                ('display_order', models.IntegerField(default=0)),
                ('source_hash', models.CharField(blank=True, db_index=True, help_text='Content hash of the source image, so re-importing updates rather than duplicates.', max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.servicecategory')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
    ]
