# Generated by Django 5.2.17 on 2026-09-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='revision',
            field=models.PositiveIntegerField(default=0, help_text='Bumped each time an issued quote is reopened for changes.'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='customer_brief',
            field=models.TextField(blank=True, help_text='What the customer wants, in their own words.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('QUOTE_RECEIVED', 'Customer — quote request received'), ('QUOTE_SENT', 'Customer — your quote is ready'), ('QUOTE_ACCEPTED', 'Customer — final quote after accepting'), ('STAFF_NEW_QUOTE', 'Staff — new quote request'), ('STAFF_QUOTE_RESPONSE', 'Staff — customer accepted or declined'), ('PAYMENT_REMINDER', 'Customer — payment reminder')], max_length=40, unique=True),
        ),
    ]
