# Generated by Django 5.2.17 on 2026-09-27 22:39

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


def verify_existing_customers(apps, schema_editor):
    """Accounts that predate ID checks keep working.

    Locking every existing customer out of quoting on deploy would hit real,
    known customers first. Staff can untick "is verified" on any account they
    do not recognise.
    """
    apps.get_model('main', 'Customer').objects.update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quote_revisions_and_briefs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Staff have checked this customer's ID. Only verified customers can request quotes."),
        ),
        migrations.AddField(
            model_name='customer',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when staff issue a temporary password; cleared once the customer picks their own.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('QUOTE_RECEIVED', 'Customer — quote request received'), ('QUOTE_SENT', 'Customer — your quote is ready'), ('QUOTE_ACCEPTED', 'Customer — final quote after accepting'), ('STAFF_NEW_QUOTE', 'Staff — new quote request'), ('STAFF_QUOTE_RESPONSE', 'Staff — customer accepted or declined'), ('APPLICATION_RECEIVED', 'Customer — account application received'), ('STAFF_NEW_APPLICATION', 'Staff — new account application'), ('ACCOUNT_APPROVED', 'Customer — account approved, sign-in details'), ('APPLICATION_REJECTED', 'Customer — account application not approved'), ('PAYMENT_REMINDER', 'Customer — payment reminder')], max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='CustomerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('id_document', models.FileField(max_length=255, storage=main.models.private_storage, upload_to=main.models.id_document_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='main.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RunPython(verify_existing_customers, migrations.RunPython.noop),
    ]
