# Generated by Django 5.2.17 on 2026-09-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='must_change_password',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('QUOTE_RECEIVED', 'Customer — quote request received'), ('QUOTE_SENT', 'Customer — your quote is ready'), ('QUOTE_ACCEPTED', 'Customer — final quote after accepting'), ('STAFF_NEW_QUOTE', 'Staff — new quote request'), ('STAFF_QUOTE_RESPONSE', 'Staff — customer accepted or declined'), ('PAYMENT_REMINDER', 'Customer — payment reminder')], max_length=40, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomerApplication',
        ),
    ]
