# Generated by Django 5.2.17 on 2026-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_customer_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Where payment reminders go when the client has no customer account.', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last payment reminder was emailed.', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('QUOTE_RECEIVED', 'Customer — quote request received'), ('QUOTE_SENT', 'Customer — your quote is ready'), ('QUOTE_ACCEPTED', 'Customer — final quote after accepting'), ('STAFF_NEW_QUOTE', 'Staff — new quote request'), ('STAFF_QUOTE_RESPONSE', 'Staff — customer accepted or declined'), ('PAYMENT_REMINDER', 'Customer — payment reminder'), ('STAFF_OVERDUE_DIGEST', 'Staff — daily overdue invoices summary')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH_CHQ', 'Cash / Cheque'), ('PO_ON_ACCOUNT', 'P.O. on account'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='', max_length=30),
        ),
    ]
